### ISSUE TITLE
Unable to immediately retype correct password after entering incorrect password

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#10]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 08/09/2021

**Description**
During user log-in, an incorrect input of a password will block the user from typing a new password in the input until the user clicks outside the application first.

**Steps to Reproduce**
1. Enter an incorrect password "12345abcd"

**Expected Results**
The user will be informed that the password entered was incorrect, then the user can re-enter the correct password.

**Actual Results**
The user was informed that the password entered was incorrect. However, the user can not immediately re-enter the correct password and must click outside the application and back to the password input before being able to type again.

**Screenshots**
![image](https://user-images.githubusercontent.com/69952593/128733029-66fed90e-7db6-44a4-847c-2d60190059dc.png)
![Screenshot (235)](https://user-images.githubusercontent.com/69952593/128733288-5a395eba-8f54-4f2b-b808-2c7eb747f92a.png)

**Comment by J-Marvin** [comment]
Fixed issue by replacing alert with modal
