### ISSUE TITLE
Prenuptial Record is successfully created but not displayed after its creation (Level 1)

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#11]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 08/10/2021

**Description**
After a successful prenuptial record creation, the main menu is immediately displayed without showing the successfully created prenuptial record.

**Steps to Reproduce**
1. Login with level 1 credentials
2. Add a valid prenuptial record and submit

**Expected Results**
The successfully created prenuptial record must be displayed.

**Actual Results**
The display immediately shows the main menu.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/128739290-c95311f2-b393-487d-a485-7f2081a70220.png)
![image](https://user-images.githubusercontent.com/69952593/128739327-442e5520-454b-4a70-884b-ce59129c1c35.png)

**Comment by J-Marvin** [comment]
Fixed by changing redirect after adding prenup
