### ISSUE TITLE
Prenuptial Record is successfully created but not displayed after its creation (Level 2 & 3)

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#12]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 08/10/2021

**Description**
After a successful prenuptial record creation, the view prenuptial records menu is immediately displayed without showing the successfully created prenuptial record.

**Steps to Reproduce**
1. Login with level 2 or 3 credentials
2. Add a valid prenuptial record and submit

**Expected Results**
The successfully created prenuptial record must be displayed.

**Actual Results**
The display immediately shows the view prenuptial records menu.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/128741701-f4e9064a-af36-4b5f-a106-80d3202c63d7.png)
![image](https://user-images.githubusercontent.com/69952593/128741751-4dad9431-d40c-4ce0-88ce-7c7fe096f358.png)

**Comment by J-Marvin** [comment]
Fixed by changing redirect after adding prenup
