### ISSUE TITLE
Member and Non-member Validation Issue # 1

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#13]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 08/10/2021

**Description**
During the creation of a prenuptial record, when the user selects a member for either groom or bride then switches to the non-member option for the input with the selected member, even if the current non-member fields are empty, the selected member will be still be recognized as an input and will lead to a successful record creation if other inputs are completely filled.

**Steps to Reproduce**
1. Login
2. Select a member for groom
3. Switch to the non-member option for the groom
4. Fill out the bride and proposed wedding date inputs
5. Submit

**Expected Results**
The user will be informed that the inputs for the groom are incomplete and should be filled.

**Actual Results**
The prenuptial record will be successfully created matching the inputs for both bride and the proposed wedding date inputs. However, the groom will have blank information.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/128809105-c588ba3e-8497-43aa-add7-63ce867c63ba.png)
![image](https://user-images.githubusercontent.com/69952593/128809133-8fd18298-b790-4635-a1ee-ccab38d90c0d.png)
![image](https://user-images.githubusercontent.com/69952593/128809172-5e127b85-0f08-4a5a-b755-a1bbb38f527f.png)

**Comment by J-Marvin** [comment]
Fixed by changing redirect after adding prenup

**Comment by francisCalimbas** [comment]
Fixed: I added other (boolean) checking in the validation and additional error messages to display if the non-member text fields are filled and the member dropdown selected value is not a blank (i.e. a member name is picked)
