### ISSUE TITLE
Member and Non-member Validation Issue # 2

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#14]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 08/10/2021

**Description**
During the creation of a prenuptial record, when the user inputs for a non-member for either groom or bride then switches to the member option for the input with the filled non-member inputs, even if the current member field is empty, the filled non-member inputs will be still be recognized and will lead to an error message outside of the validation created for the add prenuptial record form.

**Steps to Reproduce**

1. Login
2. Select non-member for bride
3. Fill all the fields with valid information
4. Switch to the member option for the bride
5. Fill out all other fields with valid information
6. Submit

**Expected Results**
The user will be informed that a member bride should be selected.

**Actual Results**
An error message outside the validation created for the add prenuptial record form will show, which will make the user unable to navigate through the application.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/128812155-69ab4c82-066c-4875-9044-bd02a542209f.png)
![image](https://user-images.githubusercontent.com/69952593/128812184-4b039b27-bae2-40b6-b7a2-4adabad575ae.png)
![image](https://user-images.githubusercontent.com/69952593/128812218-4cb5eb65-5865-44b1-80fb-3c04c6b5442d.png)

**Comment by francisCalimbas** [comment]
Fixed: Same as #13 I added other (boolean) checking in the validation and additional error messages to display if the non-member text fields are filled and the member dropdown selected value is not a blank (i.e. a member name is picked)
