### ISSUE TITLE
Edit Prenuptial Record Issue

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#15]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 08/10/2021

**Description**
When editing a prenuptial record, if a non-member is part of the prenuptial record, the inputs for the non-member is empty and can not be seen and accessed in the edit option.

**Steps to Reproduce**
1. Login with level 3 credentials
2. Edit a prenuptial record with a non-member participant

**Expected Results**
The original information must be displayed so that only the information to be edited are changed by the user.

**Actual Results**
The information for the non-member participant is blank.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/128814586-545b6e81-0ecd-46d0-bf5f-b5d0b1659537.png)
![image](https://user-images.githubusercontent.com/69952593/128814606-95f292da-5560-4a8a-a7a4-95d12e1a320c.png)

**Comment by francisCalimbas** [comment]
Fixed: the non-member partner (bride/groom) is now shown when editing a prenup record with a non-member
