### ISSUE TITLE
Records are missing date created field

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#18]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 08/16/2021

**Description**
View records are missing the date created field

**Steps to reproduce**
1. Log in with level 2 or 3 credentials
2. Go to any view records (i.e. member, prenup or child dedication)

**Expected Results**
Date created field is shown

**Actual Results**
No date created field

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/129528751-3d017c2b-7601-4b4a-8672-bf7f58fc2e3c.png)

**Comment by J-Marvin** [comment]
Fixed by uncommenting date portion in hbs files
