### ISSUE TITLE
Duplicate records are created when submit is pressed more than once

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#19]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 08/16/2021

**Description**
When creating any record, if the submit button is clicked more than once before moving to the view page, duplicate records will be created (the number will depend on how many times the submit button is clicked).

**Steps to reproduce**
1. Add any record and input all required field
2. Click submit button more than once in quick succession

**Expected Results**
Only one record will be created.

**Actual Results**
Duplicate records are created.

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/129531451-3cd7c97d-5ac3-4dba-aab1-0e35dd98aba3.png)

**Comment by J-Marvin** [comment]
Fixed by disabling button when clicked and enabling after failed ajax call

**Comment by J-Marvin** [comment]
> Fixed by disabling button when clicked and enabling after failed ajax call

Fixed duplication of records despite disabling button by disabling button upon click (previously, only disables upon valid fields)

**Comment by J-Marvin** [comment]
> > Fixed by disabling button when clicked and enabling after failed ajax call
> 
> Fixed duplication of records despite disabling button by disabling button upon click (previously, only disables upon valid fields)

Fixed duplication of records in add members, add prenup

**Comment by vanessa-tan09** [comment]
Same issue when editing a member and adding a church or observation

![image](https://user-images.githubusercontent.com/71954156/129654328-1eb2f8cb-b242-413c-ae2b-8f4337ae8abf.png)
