### ISSUE TITLE
Missing date of dedication input field in add child dedication

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#20]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 08/16/2021

**Description**
Add child dedication form is missing the date of dedication input field

**Steps to reproduce**
1. Go to add child dedication page

**Expected Results**
There is an input field for date of dedication

**Actual Results**
There is no input field for date of dedication

Screenshot
![image](https://user-images.githubusercontent.com/71954156/129535490-114ed4a8-1173-4547-866c-f606c62d431e.png)

**Comment by J-Marvin** [comment]
Added Date Field
