### ISSUE TITLE
Child dedication record successfully created with empty non-member child

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#21]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 08/16/2021

**Description**
During child dedication record creation, an empty non-member child input is accepted as a valid input.

**Steps to Reproduce**
1. Login with valid level 3 credentials
2. Go to add child dedication
3. Select non-member for the child and leave all its inputs blank
4. Fill other inputs with complete and valid information.

**Expected Results**
Program will highlight the field with missing information and prompt the user to enter information for the field.

**Actual Results**
A child dedication record is successfully created.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/129546638-fcbcbdbf-249f-4db3-a698-2819f0f187eb.png)

**Comment by J-Marvin** [comment]
Fixed front end validation for non-member child
