### ISSUE TITLE
Child dedication record with no parent inputs shows error message but successfully creates record

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#22]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 08/16/2021

**Description**
During child dedication record creation, a creation form with other inputs filled and the parent inputs blank being submitted would cause an error message display, but a record is successfully created.

**Steps to Reproduce**
1. Login with valid level 3 credentials
2. Go to add child dedication
3. Fill other inputs with complete and valid information
4. Leave both parent inputs blank

**Expected Results**
The fields for both parents must be highlighted and the user is informed to provide the needed information.

**Actual Results**
An error message is displayed but a record is successfully created.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/129559358-0951b114-ed3e-464d-909f-62ded2317f52.png)
![image](https://user-images.githubusercontent.com/69952593/129559403-54310dd0-4d2e-454d-b20e-dfc4cb050ef1.png)
![image](https://user-images.githubusercontent.com/69952593/129559486-d17e7ecf-b2f5-4794-9530-b94cf6856c28.png)

**Comment by J-Marvin** [comment]
Fix parent/guardian validation bug (caused by selectize)
