### ISSUE TITLE
Child dedication and Prenup accepts middle initial with more than 1 character

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#25]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 08/17/2021

**Description**
When adding a non-member in child dedication or prenup, all the middle initial fields accept more than 1 character.

**Steps to reproduce**
1. Go to add child dedication or add prenup
2. Select non-members for any person field (child, parent, witness, bride or groom)
3. Enter more than 1 character for middle initial field
4. Submit

**Expected Results**
Middle initial with more than 1 character will not be accepted.

**Actual Results**
No validation for middle initial and record was created.

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/129655429-baf84ec4-eb5b-4173-a69c-48ddcf4ceaaf.png)
![image](https://user-images.githubusercontent.com/71954156/129655430-1cb7f958-0d00-443a-9319-919cbcf8f498.png)

**Comment by francisCalimbas** [comment]
Fixed by adding middle initial validations (checks both length and if the character is a letter)

**Comment by vanessa-tan09** [comment]
> Fixed by adding middle initial validations (checks both length and if the character is a letter)

Works for child and witness. But, when I try it on the parents, the error message shows up but the record is still created.
![image](https://user-images.githubusercontent.com/71954156/129738009-52c24acc-9f80-4e79-931e-35f0507a58fb.png)
![image](https://user-images.githubusercontent.com/71954156/129738014-6564b06f-5c2d-46d3-9486-131094d72c26.png)

**Comment by francisCalimbas** [comment]
Fixed by adding forgotten boolean flag variables in middle initial validations (P.S. my mistake I forgot HAHA)
