### ISSUE TITLE
View wedding record is missing date created

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#27]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 08/24/2021

**Description**
View wedding record does not show the date the record was created

**Steps to reproduce**
1. Log in with level 2 or 3 credentials
2. Go to view wedding record

**Expected Results**
Date created field is shown

**Actual Results**
No date created field

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/130569737-f3f30be5-2c04-4e47-b3f4-5f6a3f337f5c.png)

**Comment by francisCalimbas** [comment]
Fixed by including the date created field in the view-wedding frontend
