### ISSUE TITLE
With level 1 credentials, clicking back button in wedding register will log me in as level 3

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#29]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 08/24/2021

**Description**
With a level 1 credential, if I go to add wedding register then click the back button, I will be redirected to the view that shows all the wedding records as if I have level 3 credentials. If from the wedding register I click the name of the church in the navbar, the system will redirect me to the front page and in the navbar it shows that I am logged in as level 3.

**Steps to reproduce**
1. Log in with level 1 credential
2. Go to add wedding record
3. Click back button (goes to view all wedding records page and gives me level 3 access)
4. Or Click navbar (goes to front page and shows that I'm logged in at level 3 and gives me level 3 access)

**Expected Results**
Retain level 1 access

**Actual Results**
Given level 3 access

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/130611882-a9d3345b-58e5-47a9-9a10-ab72cb7fae59.png)

**Comment by J-Marvin** [comment]
Fixed by removing code for debugging
