### ISSUE TITLE
Associated wedding record does not show in the view members page

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#30]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 08/24/2021

**Description**
The linked wedding record for the member is not shown in the view members page

**Steps to reproduce**
1. Log in with level 2 or 3 credentials
2. Go to add wedding record and create a wedding record where either the bride or groom is a member
3. Submit
4. Go to view members page of the bride or groom

**Expected Results**
The link to the wedding record is shown in the view members page

**Actual Results**
The link to the wedding record is not shown in the view members page

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/130622385-5a2d8b36-b890-43dc-b976-45c9219f8180.png)

**Comment by J-Marvin** [comment]
Fixed by adding to wedding link to member page

**Comment by vanessa-tan09** [comment]
> Fixed by adding to wedding link to member page
