### ISSUE TITLE
Baptismal location not shown in view baptismal record page

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#33]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 09/02/2021

**Description**
The baptismal location is not shown in the view baptismal record page

**Steps to reproduce**
1. Log in with level 2 or 3 credentials
2. Go to baptismal records
3. View any baptismal record

**Expected Results**
The baptismal location is shown in the view baptismal record page

**Actual Results**
The baptismal record is not shown in the view baptismal record page

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/131837444-14c7a8d7-26e7-4a45-ac02-f548e7c146ff.png)

**Comment by francisCalimbas** [comment]
Added the location below the officiant's name
