### ISSUE TITLE
Unauthorized access when pressing back button in advanced search

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#34]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 09/06/2021

**Description**
In  the advanced search page, when the back button in the navbar is pressed, an unauthorized access error message is shown.

**Steps to reproduce**
1. Log in with level 2 or 3 credentials
2. Go to advanced search page
3. Press the back button in the navbar

**Expected Results**
Goes back to previous page

**Actual Results**
Shows unauthorized access  error

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/132150963-ba841fc0-463b-4bfb-bbf8-0d23c0d2b239.png)

**Comment by francisCalimbas** [comment]
Fixed the typo in advanced search backLink
