### ISSUE TITLE
Unauthorized access when adding baptismal record from the view member page

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#35]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 09/06/2021

**Description**
In the view member page, when the add baptismal button is clicked, an unauthorized access error message is shown.

**Steps to reproduce**
1. Log in with level 2 or 3 credentials
2. Go to view member page
3. Click the Add baptismal button

**Expected Results**
Goes to add baptismal record page

**Actual Results**
Shows unauthorized access  error

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/132155029-9591de85-3b16-4324-8601-78b12483de63.png)

**Comment by J-Marvin** [comment]
Fixed wrong link in view member page
