### ISSUE TITLE
No link to child dedication record from the view member page

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#36]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 09/06/2021

**Description**
In the view member page, the link to the associated child dedication record is not accessible.

**Steps to reproduce**
1. Log in with level 2 or 3 credentials
2. Go to view member page

**Expected Results**
A link to the associated child dedication record is available.

**Actual Results**
No link to the associated child dedication record

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/132155601-ef1b6e86-d4d3-4367-8a8d-fc3923cdddc9.png)

**Comment by J-Marvin** [comment]
Fixed by linking child dedication to member
