### ISSUE TITLE
No search results when civil status is 'Others'

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#38]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 09/06/2021

**Description**
When civil status is others, no search results even if there is a member that match the search criteria

**Steps to reproduce**
1. Log in with level 2 or 3 credentials
2. Go to advanced search
3. Select Others in Civil Status Field

**Expected Results**
Show members with others as civil status

**Actual Results**
Empty search results

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/132169690-4549da67-abab-4e53-b207-a06b5f13bb51.png)
![image](https://user-images.githubusercontent.com/71954156/132169697-e1d99c76-c80d-42ee-9e22-99d3095aa2e3.png)

**Comment by francisCalimbas** [comment]
Fixed a condition when civil status is 'Others'
