### ISSUE TITLE
Search Baptismal Record Date not inclusive

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#39]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 09/06/2021

**Description**
The To field for the date of the baptism is not inclusive (i.e. does not show the records if the date of baptism is exactly the date entered in the To field) 

**Steps to reproduce**
1. Log in with level 2 or 3 credentials
2. Go to advanced search
3. Select baptismal record

**Expected Results**
To field for the date of baptism is inclusive.

**Actual Results**
To field for the date of baptism is not inclusive.

**Screenshot**
All baptism records
![image](https://user-images.githubusercontent.com/71954156/132191214-8db6bb5f-d9c0-4f4a-85b8-e072b388c157.png)
Input
![image](https://user-images.githubusercontent.com/71954156/132191200-59c11552-0153-477e-8504-6809d3809a99.png)
Results (missing IDs 3000003 and 3000004)
![image](https://user-images.githubusercontent.com/71954156/132191226-60a1e0f7-b423-4769-ac96-87635e0e3ee0.png)

**Comment by J-Marvin** [comment]
Fixed conditions with dates
