### ISSUE TITLE
Can't open member record with level 2 credentials

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#42]
**Reporter**: Tan, Vanessa Marie C.
**Report Date**: 09/08/2021

**Description**
Can't open member record when logged in with level 2 credentials.

**Steps to Reproduce**
1. Log in with level 2 credentials.
2. Go to members
3. Click a member record

**Expected Results**
Member record will be opened and is viewable

**Actual Results**
Nothing happens when clicked

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/132485074-59d47cf6-f9c8-4d1d-8856-b12550753fa1.png)

**Comment by francisCalimbas** [comment]
Fixed the error by including handlebars if-conditions
