### ISSUE TITLE
Child and parent/guardian in edit child dedication can be the same member

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#44]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 09/11/2021

**Description**
When editing a child dedication record, it is possible for an edited child dedication record to result to a record with the same child and parent/guardian.

**Steps to Reproduce**
1. Enter password: Coffee118
2. Go to Registries page
3. Go to Child Dedication page
4. Select a child dedication record
5. Go to edit dedication form
6. Edit either the child or parent/guardian

**Expected Results**
The member child or parent/guardian can not be select by the user in the other category.

**Actual Results**
The member child or parent/guardian can be selected by the user in the other category which can result to the same member child and parent/guardian.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/132948600-db991718-531d-4078-9771-c8dd5658b1c2.png)

**Comment by J-Marvin** [comment]
Fixed issue with initializing options
