### ISSUE TITLE
Unauthorized access when going to the baptismal record using level 1 credentials

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#45]
**Reporter**: Tan, Vanessa Marie C.
**Report Date**: 09/11/2021

**Description**
Error message: Unauthorized access when trying to go to the baptismal record page using level 1 credentials.

**Steps to Reproduce**
1. Log in with level 1 credentials.
2. Go to registries 
3. Go to baptismal record

**Expected Results**
Go to add baptismal record page

**Actual Results**
Unauthorized access

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/132949244-0e11d7bd-e014-489c-a098-abed123a53ac.png)

**Comment by J-Marvin** [comment]
Fixed error in accessing add baptismal
