### ISSUE TITLE
Child dedication record's address of dedication does not change when edited

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#47]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 09/11/2021

**Description**
When changing the child dedication record's address of dedication, the changes made by the user are unsuccessful.

**Steps to Reproduce**
1. Enter password: Coffee118
2. Go to Registries page
3. Go to Child Dedication page
4. Select a child dedication record
5. Go to edit dedication form
6. Change the current address of dedication
7. Submit

**Expected Results**
The input of the user for address of dedication will be successfully changed in the database and displayed after the user submits the edit dedication form.

**Actual Results**
The address of dedication remains the same even after changing the current address of dedication and submitting the edit dedication form.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/132951117-e2b6f7f8-de0d-4b39-a76c-29ba2e90381f.png)
![image](https://user-images.githubusercontent.com/69952593/132951178-acbebf43-fef5-444a-8260-e386c3d7c5ea.png)
![image](https://user-images.githubusercontent.com/69952593/132951209-6b477a96-ce98-411c-95e9-c8a358168108.png)

**Comment by francisCalimbas** [comment]
Added a fix, wrong id is accessed to address input field
