### ISSUE TITLE
Parent/guardian member can be selected for godmother and godfather

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#48]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 09/11/2021

**Description**
When adding an additional godmother or godfather to the dedication record, the user can add the child's first and second parent/guardian.

**Steps to Reproduce**
1. Enter password: Coffee118
2. Go to Registries page
3. Go to Child Dedication page
4. Select a child dedication record
5. Go to edit dedication form
6. Add member godmother/godfather

**Expected Results**
The child's first and second parent/guardian can not be selected as an additional godmother or godfather.

**Actual Results**
The child's first and second parent/guardian can be selected as additional godmother and godfather. 

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/132951561-ea8b52f9-fce8-4eb4-902d-316e3e6c11ce.png)

**Comment by J-Marvin** [comment]
Fixed issue by replacing wrong ids
