### ISSUE TITLE
Godfather section shows need atleast 1 godfather even when there is an existing godfather or atleast one existing godmother

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#50]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 09/11/2021

**Description**
When editing a child dedication record, the error message "Need at least 1 Godfather/Godmother"  is displayed even when there is an existing godfather or godmother in the record.

**Steps to Reproduce**
1. Enter password: Coffee118
2. Go to Registries page
3. Go to Child Dedication page
4. Select a child dedication record with either one godfather or godmother
5. Go to edit dedication form
6. Submit

**Expected Results**
Submission will be accepted

**Actual Results**
Error message "Need at least 1 Godfather" or "Need at least 1 Godmother" is displayed

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/132953430-b08f4bea-db49-4932-a950-abc7a01b4cf7.png)
![image](https://user-images.githubusercontent.com/69952593/132953517-92c0d757-c73f-43de-96a9-8e343afaa65d.png)

**Comment by francisCalimbas** [comment]
Pushed a fix on validation conditions

**Comment by francisCalimbas** [comment]
> Pushed a fix on validation conditions
Wait wait sorry wag muna @JohnBainto

**Comment by J-Marvin** [comment]
Fixed witness counters
