### ISSUE TITLE
Wedding date field in edit wedding page is initially set to the date created

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#51]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 09/12/2021

**Description**
When editing a wedding record, the wedding date field is initially set to the date created instead of the wedding date entered in the original  record.

**Steps to reproduce**
1. Go to wedding record
2. Edit wedding record

**Expected Results**
The wedding date is initially set to the wedding date of the original record.

**Actual Results**
The wedding date is initially set to the date created

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/132990579-d721aa82-6e23-47bd-8f74-2f6282f2e5aa.png)
![image](https://user-images.githubusercontent.com/71954156/132990719-41d591c9-6ed7-4986-a32b-2868a5e28951.png)

**Comment by francisCalimbas** [comment]
Applied a fix (misplaced variable in hbs)
