### ISSUE TITLE
Non-member groom field in edit wedding record does not have an initial value

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#52]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 09/12/2021

**Description**
When trying to edit a non-member groom, the middle initial and last name fields are not automatically filled out initially.

**Steps to reproduce**
1. Go to wedding record
2. Edit wedding record
3. Edit a non-member groom

**Expected Results**
The middle initial and last name field are automatically filled out.

**Actual Results**
The middle initial and last name field are not automatically filled out.

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/132991840-a72cd74a-a511-4a1f-b74c-56564554b920.png)
![image](https://user-images.githubusercontent.com/71954156/132991846-329c03be-541e-4c21-99c1-c333480cb262.png)

**Comment by vanessa-tan09** [comment]
Similar issue: Initial value set for non-member groom's mother has whitespaces before the names.
![image](https://user-images.githubusercontent.com/71954156/132992386-20c373dd-0a31-430a-86c6-6e9b855debfa.png)

**Comment by J-Marvin** [comment]
Fixed displaying of non-member groom and groom mother
