### ISSUE TITLE
After editing bride's/groom's mother, the save changes button for the bride's/groom's father is disabled

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#53]
**Reporter:** Tan, Vanessa Marie C.
**Report date:** 09/12/2021

**Description**
The save changes button for editing the bride's or groom's father becomes disabled after editing the bride's or groom's mother.

**Steps to reproduce**
1. Go to a wedding record
2. Edit wedding record
3. Edit bride's or groom's mother
4. Edit bride's or groom's father

**Expected Results**
Can still edit the bride's or groom's father.

**Actual Results**
Cannot still edit the bride's or groom's father.

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/132992062-472d85f6-b399-478e-a736-e27ebea483ca.png)

**Comment by francisCalimbas** [comment]
Applied a fix
