### ISSUE TITLE
Editing a prenuptial record using a level 2 user leads to a level 3 user

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#54]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 09/13/2021

**Description**
Being a level 2 user and editing a prenuptial record leads to the user having access as a level 3 user.

**Steps to Reproduce**
1. Enter password: HelloSweng
2. Go to Registries page
3. Go to Child Dedication page
4. Select a child dedication record
5. Go to edit dedication form
6. Submit
7. Return to main menu
8. Go to Members page
9. Select a member
10. Go to edit member page

**Expected Results**
The user will not be able to access the edit member page

**Actual Results**
The user has access to editing a member

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/133002032-9e985429-e8b8-4bff-b226-973353f72e06.png)
![image](https://user-images.githubusercontent.com/69952593/133002066-9b09ee67-152a-438d-b384-1650d9e43252.png)
![image](https://user-images.githubusercontent.com/69952593/133002075-77493030-fffb-4ae4-8f08-a721c0dc275d.png)

**Comment by J-Marvin** [comment]
Removed code changing session level in edit dedication
