### ISSUE TITLE
After editing a prenuptial record once, the planned wedding date becomes empty during the second attempt

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#56]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 09/13/2021

**Description**
After editing and submitting an edit in a prenuptial record once, the planned wedding date becomes empty which requires the user to re-enter the previous entered wedding date.

**Steps to Reproduce**
1. Enter password: Coffee118
2. Go to registries page
3. Go to prenuptial record page
4. Select a prenuptial record
6. Go to edit prenuptial record
7. Submit
8. Edit the same prenuptial record
9. Submit

**Expected Results**
The original planned wedding date would still be there allowing the user to submit without re-entering the current planned wedding date.

**Actual Results**
The planned wedding date after the first attempt will be blank requiring the user to re-enter the planned wedding date of the selected prenuptial record.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/133091048-dc91482d-3e21-4e4a-a61a-79b31a424b20.png)
![image](https://user-images.githubusercontent.com/69952593/133091111-36fe975f-f8c9-4b16-b14a-cde202862aeb.png)
![image](https://user-images.githubusercontent.com/69952593/133091189-4ddcb158-fb90-49e4-9e0c-06506b760087.png)

**Comment by francisCalimbas** [comment]
Applied a fix, automatically sets the wedding date input
