### ISSUE TITLE
Middle initial in child, first and second parent/guardian can have multiple letters when editing a child dedication record

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#58]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 09/13/2021

**Description**
When editing a child dedication record, the user can input multiple letters for the middle initial of a non-member child, and parents/guardians.

**Steps to Reproduce**
1. Enter password: Coffee118
2. Go to Registries page
3. Go to Child dedication record page
4. Select a child dedication record
5. Go to edit child dedication record
6. Input the following information:
Child: [Non-member] Isaac Cl Clarke
First Parent/Guardian: [Non-member] Liara Ba Tsoni
Second Parent/Guardian: [Non-member] Garrus Ak Vakarian
Godmother: [Non-member] Nino Na Nakano
Godfather: [Non-member] {empty inputs}
7. Submit

**Expected Results**
A warning will be shown to the user and the current changes entered by the user will not be applied.

**Actual Results**
The incorrect changes made by the user is accepted and is applied as a change to the selected child dedication record.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/133105507-669549e3-479b-460f-ac4b-4244d5714743.png)

**Comment by francisCalimbas** [comment]
Added middle initial validations
