### ISSUE TITLE
Middle initial in a non-member bride can have multiple letters when editing a prenuptial record

### ISSUE THREAD

**Issue by JohnBainto** [J-Marvin/CSSWENG-AY2021T3-S11-G3#59]
**Reporter**: Bainto, John Matthew dL.
**Report Date**: 09/13/2021

**Description**
When editing a prenuptial record, a non-member bride can have multiple letters as input for their middle initial and will be accepted as a change.

**Steps to Reproduce**
1. Enter password: Coffee118
2. Go to Registries page
3. Go to Prenuptial record page
4. Select a prenuptial record
5. Go to edit prenuptial record
6. Input the following information:
Bride: [Non-member] Liara Bi Tsoni
Groom: [Non-member] Garrus Va Vakarian
7. Submit

**Expected Results**
A warning will be shown informing the user that a middle initial with multiple letters is not allowed.

**Actual Results**
An input with multiple letters for a non-member bride is accepted as a valid change to the prenuptial record.

**Screenshot**
![image](https://user-images.githubusercontent.com/69952593/133109106-7998f050-fcab-4843-bab2-e15bafb18eaa.png)

**Comment by francisCalimbas** [comment]
Added middle initial validations
