### ISSUE TITLE
Unauthorized Access Error after pressing back button

### ISSUE THREAD

**Issue by vanessa-tan09** [J-Marvin/CSSWENG-AY2021T3-S11-G3#9]
**Reporter:** Tan, Vanessa Marie C.
**Report Date:** 08/09/2021

**Description**
If logged in using level 1 credentials
After submitting the add member form, pressing the back button in the view member page shows an error: Unauthorized Access

**Steps to Reproduce**
1. Login with level 1 credentials
2. Add a member and submit
3. From the view member page, press the back button

**Expected Results**
Go back to the home page (page where user can add member or form)

**Actual Results**
Shows Error 401: Unauthorized Access

**Screenshot**
![image](https://user-images.githubusercontent.com/71954156/128713307-ec8bffb5-5bb4-4336-8540-cff95d27eac4.png)

**Comment by J-Marvin** [comment]
Fixed by adding custom previous links
